-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EchoDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EchoDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EchoDB` DEFAULT CHARACTER SET utf8 ;
USE `EchoDB` ;

-- -----------------------------------------------------
-- Table `EchoDB`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EchoDB`.`USER` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(25) NOT NULL,
  `PASSWORD` VARCHAR(25) NOT NULL,
  `FIRST_NAME` VARCHAR(25) NOT NULL,
  `LAST_NAME` VARCHAR(25) NOT NULL,
  `CELL_NUM` VARCHAR(10) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC),
  UNIQUE INDEX `CELL_NUM_UNIQUE` (`CELL_NUM` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EchoDB`.`CONVERSATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EchoDB`.`CONVERSATION` (
  `CONVERSATION_ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`CONVERSATION_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EchoDB`.`MESSAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EchoDB`.`MESSAGE` (
  `MESSAGE_ID` INT NOT NULL AUTO_INCREMENT,
  `MESSAGE_DATE_TIME` DATETIME NOT NULL,
  `MESSAGE_TEXT` LONGTEXT NULL,
  `MESSAGE_IMAGE` VARCHAR(50) NULL,
  `MESSAGE_VIDEO` VARCHAR(50) NULL,
  `MESSAGE_AUDIO` VARCHAR(50) NULL,
  `USER_ID_SENT` INT NOT NULL,
  `CONVERSATION_ID` INT NOT NULL,
  PRIMARY KEY (`MESSAGE_ID`),
  INDEX `fk_MESSAGE_USER_idx` (`USER_ID_SENT` ASC),
  INDEX `fk_MESSAGE_CONVERSATION1_idx` (`CONVERSATION_ID` ASC),
  CONSTRAINT `fk_MESSAGE_USER`
    FOREIGN KEY (`USER_ID_SENT`)
    REFERENCES `EchoDB`.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MESSAGE_CONVERSATION1`
    FOREIGN KEY (`CONVERSATION_ID`)
    REFERENCES `EchoDB`.`CONVERSATION` (`CONVERSATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EchoDB`.`CONVERSATION_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EchoDB`.`CONVERSATION_USER` (
  `CONVERSATION_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`CONVERSATION_ID`, `USER_ID`),
  INDEX `fk_CONVERSATION_USER_CONVERSATION1_idx` (`CONVERSATION_ID` ASC),
  INDEX `fk_CONVERSATION_USER_USER1_idx` (`USER_ID` ASC),
  CONSTRAINT `fk_CONVERSATION_USER_CONVERSATION1`
    FOREIGN KEY (`CONVERSATION_ID`)
    REFERENCES `EchoDB`.`CONVERSATION` (`CONVERSATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONVERSATION_USER_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `EchoDB`.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
